name: Configuration Rewrite
type: module
description: Changes configuration YAML from config/install|optional with YAML from config/rewrite.
# core: 8.x
package: Configuration

# Information added by Drupal.org packaging script on 2016-10-31
version: '8.x-1.0-beta1'
core: '8.x'
project: 'config_rewrite'
datestamp: 1477948465
