<?php

/**
 * @file
 * Allow configuring and hiding fields from node forms via theme configuration.
 */

use Drupal\Core\Access\AccessResultForbidden;
use Drupal\Core\Access\AccessResultNeutral;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_field_access().
 */
function theme_content_structure_restrict_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {

  // If there are fields defined, check and restrict access.
  if ($fields_to_restrict = theme_content_structure_restrict_get_restrictions('fields')) {
    $field_name = $field_definition->getName();

    if (in_array($operation, array('edit', 'created')) && in_array($field_name, $fields_to_restrict)) {
      return new AccessResultForbidden();
    }
  }

  // No fields were detected, maybe we dont have fields restrictions YML
  // for this theme, or there are no restrictions defined in the YML file.
  // Either case, proceed as normal.
  return new AccessResultNeutral();
}


/**
 * Implements hook_ENTITYTPE_create_access().
 */
function theme_content_structure_restrict_node_create_access(\Drupal\Core\Session\AccountInterface $account, array $context, $entity_bundle) {

  // If there are cts defined, check and restrict access.
  if ($cts_to_restrict = theme_content_structure_restrict_get_restrictions('cts')) {
    if (in_array($entity_bundle, $cts_to_restrict)) {
      return new AccessResultForbidden();
    }
  }

  // No cts were detected, maybe we dont have fields restrictions YML
  // for this theme or there are no restrictions defined in the YML file.
  // Either case, proceed as normal.
  return new AccessResultNeutral();
}


/**
 * Access helper function.
 */
function theme_content_structure_restrict_get_restrictions($restriction_type = 'fields') {
  $config = \Drupal::config('system.theme');
  $default_theme = $config->get('default');

  // Get the list of fields which should be hidden
  // from file named as example: tcsr.bartik.settings.
  $config = \Drupal::config('theme_content_structure_restrict.' . $default_theme . '.settings');
  $restrictions = $config->get('theme_content_structure_restrict_' . $restriction_type);

  if (!empty($restrictions)) {
    return $restrictions;
  }
}
