<?php
/**
 * @file
 * Code for the T&L Options Preview Block module.
 */

/**
 * Implements hook_theme().
 */
function tl_options_preview_block_theme($existing, $type, $theme, $path) {
  return [
    'tl_options_preview_block' => [
      'variables' => [
        'title' => [],
        'content' => [],
        'tab' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function tl_options_preview_block_page_attachments_alter(&$page) {
  $page['#attached']['library'][] = 'tl_options_preview_block/tl_options_preview_block';
}
