project:
    machine_name: tlweb
    prefix: TLWeb
    human_name: 'Tate and Lyle'
    profile:
        name: lightning
    local:
        protocol: http
        hostname: '${project.machine_name}.local'
git:
    default_branch: master
    remotes:
        - 'tatelylecom@svn-19900.prod.hosting.acquia.com:tatelylecom.git'
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend-setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend-build configured.'''
    post-deploy-build:
        dir: '${docroot}'
        command: 'echo ''No post-deploy build configured.'''
    post-setup-build:
        dir: '${docroot}'
        command: 'echo ''No post-setup build configured.'''
import: null
modules:
    ci:
        enable: {  }
        uninstall: [acquia_connector, shield]
    deploy:
        enable: [acquia_connector, shield, admin_toolbar]
        uninstall: [devel, field_ui, views_ui]
    local:
        enable: [dblog, devel, field_ui, seckit, views_ui, admin_toolbar]
        uninstall: [acsf, acquia_connector, dblog, shield]

