<?php
/**
 * @file
 * Code for the T&L form tweaks module.
 */

/**
 * Implements hook_form_alter().
 */
function tl_form_tweaks_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (($form['#form_id'] == 'contact_message_contact_us_form') || ($form['#form_id'] == 'contact_message_file_access_form') || ($form['#form_id'] == 'contact_message_marketing_form')) {
    $form['actions']['submit']['#value'] = t('Send');
    unset($form['actions']['preview']);
  }

  if ($form['#form_id'] == 'contact_message_confirmation_form') {
    $form['actions']['submit']['#value'] = t('Proceed to submission form');
    unset($form['actions']['preview']);
  }

  if ($form['#form_id'] == 'contact_message_innovation_submission_form') {
    $form['actions']['submit']['#value'] = t('Submit');
    unset($form['actions']['preview']);
  }

}
