<?php
/**
 * @file
 * Code for the T&L Tweaks module.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_page_attachments_alter().
 */
function tl_tweaks_dolciaprima_page_attachments_alter(&$page) {
  $page['#attached']['library'][] = 'tl_tweaks_dolciaprima/tl_tweaks_dolciaprima';
}

/**
 * Implements hook_node_load().
 */
function tl_tweaks_dolciaprima_node_load($nodes, $types = NULL) {
  foreach ($nodes as $key => $node) {
    if ($nodes[$key]->getType() == 'form') {
      if ($node->get('field_form')->getValue()[0]['target_id'] == "technical_data_sheets") {
        if (isset(Html::escape($_GET['submitted']))) {
          if (Html::escape($_GET['submitted']) == 'true') {
            $node->set('field_form_header', "", $notify = TRUE);
            $node->set('field_form', "", $notify = TRUE);
          }
        }
        \Drupal\Core\Cache\Cache::invalidateTags($node->getCacheTags());
      }
    }
  }
}
