<?php

/**
 * @file
 * Contains tal_articles.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_alter().
 */
function tal_articles_form_views_exposed_form_alter(&$form, FormStateInterface $form_state) {
  if ($form['#id'] == 'views-exposed-form-article-list-page-1') {
    $form['actions']['submit']['#attributes'] = array('class' => array('hide'));
    $form['sort_by']['#attributes'] = array('onchange' => array('this.form.submit();'));
  }
}

/**
 * Implements hook_views_pre_view().
 */
function tal_articles_views_pre_view(ViewExecutable $view, $display_id, array &$args) {

  // Modify contextual filters for article list if term name is "Company news"'.
  if ($view->id() == 'article_list' &&  $display_id == 'page_1') {
    if ($args[0] != 'all') {
      // Load all terms from media gallery vocabulary.
      $term = Term::load($args[0]);
      if ($term->getName() == 'Company Story') {
        $terms = \Drupal::service('entity_type.manager')
          ->getStorage("taxonomy_term")
          ->loadTree('story_category');

        foreach ($terms as $trm) {
          if ($trm->name == 'Case Study') {
            break;
          }
        }
        $args[0] = $args[0] . '+' . $trm->tid;
      }
    }
  }
}
