<?php

/**
 * @file
 * Tal webform module.
 */

use Drupal\Core\Form\FormStateInterface;
use Symfony\Cmf\Component\Routing\RouteObjectInterface;

/**
 * Implements hook_form_alter().
 */
function tal_webform_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_contact_form_form') {
    $request = \Drupal::request();
    // Check if current path is admin.
    $route_match = \Drupal::service('router.no_access_checks')->matchRequest($request);
    $route = $route_match[RouteObjectInterface::ROUTE_OBJECT];
    $is_admin = \Drupal::service('router.admin_context')->isAdminRoute($route);
    if (!$is_admin) {
      $route_match = \Drupal::routeMatch();
      $title = \Drupal::service('title_resolver')->getTitle($request, $route_match->getRouteObject());
      $form['elements']['page_title']['#default_value'] = $title;
    }
  }
  if (strpos($form_id, 'webform_submission_') !== FALSE) {
    honeypot_add_form_protection($form, $form_state, ['honeypot', 'time_restriction']);
  }
}
