<?php

/**
 * @file
 * Module file for functionality.
 */

use Drupal\Core\Menu\MenuTreeParameters;

/**
 * Implements hook_theme().
 */
function tal_mega_menu_theme() {
  return array(
    'tal_mega_menu' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'tal_menu_col_level1' => [
      'variables' => [
        'link' => NULL,
        'level' => NULL,
        'data' => NULL,
      ],
    ],
    'tal_menu_col_level2' => [
      'variables' => [
        'link' => NULL,
        'level' => NULL,
        'data' => NULL,
      ],
    ],
    'tal_menu_col_list_level3' => [
      'variables' => [
        'link' => NULL,
        'desc' => NULL,
        'level' => NULL,
      ],
    ],
  );
}

/**
 * Function to get the all menu items.
 *
 * @return mixed
 *   Mixed array containing all menu items.
 */
function tal_mega_menus_build_tree($block_config) {
  $menu_tree = \Drupal::menuTree();
  $parameters = new MenuTreeParameters();
  // Set menu depth.
  $parameters->setMaxDepth($block_config['depth']);
  $parameters->excludeRoot()->onlyEnabledLinks();
  $tree = $menu_tree->load($block_config['menu_name'], $parameters);
  $manipulators = array(
    array('callable' => 'menu.default_tree_manipulators:checkAccess'),
    array('callable' => 'menu.default_tree_manipulators:generateIndexAndSort'),
    array('callable' => 'toolbar_tools_menu_navigation_links'),
  );
  $tree = $menu_tree->transform($tree, $manipulators);
  return $menu_tree->build($tree);
}
