project:
  machine_name: tatelylecom
  prefix: TAL
  human_name: 'Tate and Lyle.Com'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: '${project.machine_name}.local'
git:
  default_branch: master
  remotes:
    - 'tatelylecom@svn-19900.prod.hosting.acquia.com:tatelylecom.git'
    - 'git@github.com:acquia-pso/tateandlyle.git'
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
target-hooks:
  frontend-setup:
    dir: '${docroot}'
    command: 'echo ''No  frontend-setup configured.'''
  frontend-build:
    dir: '${docroot}'
    command: 'echo ''No frontend-build configured.'''
  pre-config-import:
    dir: '${docroot}'
    command: 'echo ''No pre-config-import configured.'''
  post-deploy-build:
    dir: '${docroot}'
    command: 'echo ''No post-deploy build configured.'''
  post-setup-build:
    dir: '${docroot}'
    command: 'echo ''No post-setup build configured.'''
import: '${repo.root}/blt/build.xml'
modules:
  local:
    enable: [dblog, acquia_connector, devel, field_ui, seckit, views_ui, features_ui]
    uninstall: [acsf, dblog, shield, simplesamlphp_auth]
  ci:
    enable: {  }
    uninstall: [shield]
  dev:
    enable: [acquia_connector, shield,simplesamlphp_auth]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield, syslog, dynamic_page_cache, seckit, simplesamlphp_auth]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield, syslog, dynamic_page_cache, seckit]
    uninstall: [dblog, devel, views_ui]
  deploy:
    enable: [acquia_connector, admin_toolbar]
    uninstall: {  }
behat:
  paths:
    - '${repo.root}/tests/behat'
simplesamlphp: 'true'

