name: 'T&L Translation Settings'
type: module
core: 8.x
dependencies:
  - block
  - block_content
  - content_translation
  - entity_reference_revisions
  - field
  - file
  - language
  - menu_link_content
  - paragraphs
  - redirect
  - shortcut
  - user
  - views
  - workbench_moderation
version: 8.x-1.0
