<?php

/**
 * @file
 * Contains all hooks related to  TAL Downloads functionality.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Prepares variables for file link templates.
 *
 * Default template: tal-download-link.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - file: A file object to which the link will be created.
 *   - icon_directory: (optional) A path to a directory of icons to be used for
 *     files. Defaults to the value of the "icon.directory" variable.
 *   - description: A description to be displayed instead of the filename.
 *   - attributes: An associative array of attributes to be placed in the a tag.
 */
function template_preprocess_tal_download_link(array &$variables) {
  $file_entity = $variables['file'];
  $options = array();

  $file_size = $file_entity->getSize();
  $url = file_create_url($file_entity->getFileUri());
  $variables['#cache']['contexts'][] = 'url.site';

  $mime_type = $file_entity->getMimeType();
  // Set options as per anchor format described at
  // http://microformats.org/wiki/file-format-examples
  $options['attributes']['type'] = $mime_type . '; length=' . $file_entity->getSize();

  // Use the description as the link text if available.
  $link_text = t('Downloads');

  // Classes to add to the file field for icons.
  $classes = array(
    'file',
    // Add a specific class for each and every mime type.
    'file--mime-' . strtr($mime_type, array('/' => '-', '.' => '-')),
    // Add a more general class for groups of well known MIME types.
    'file--' . file_icon_class($mime_type),
  );

  $variables['link'] = Link::fromTextAndUrl($link_text, Url::fromUri($url, $options));
  $variables['file_size'] = format_size($file_size);

  // Set file classes to the options array.
  $variables['attributes'] = new Attribute($variables['attributes']);
  $variables['attributes']->addClass($classes);
}

/**
 * Implements hook_theme().
 */
function tal_downloads_theme() {
  return array(
    'tal_download_link' => array(
      'variables' => array(
        'file' => NULL,
        'attributes' => array(),
      ),
    ),
  );
}
