<?php

/**
 * @file
 * Contains access_unpublished implementations.
 */

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Access\AccessResult;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Session\AccountInterface;
use \Drupal\Core\Url;
use \Drupal\node\NodeInterface;
use \Drupal\Core\Entity\EntityForm;

/**
 * Implements hook_entity_access().
 */
function access_unpublished_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {

  $tokenKey = \Drupal::config('access_unpublished.settings')->get('hash_key');

  if (
    $operation == 'view' &&
    \Drupal::request()->query->has($tokenKey) &&
    // @todo: For 8.3 this should check for EntityPublishedInterface.
    $entity instanceof NodeInterface &&
    $account->hasPermission('access_unpublished ' . $entity->getEntityTypeId() . ' ' . $entity->bundle()) &&
    !$entity->isPublished()
  ) {

    $query = \Drupal::entityQuery('access_token');
    $tokens = $query->condition('entity_type', $entity->getEntityType()->id())
      ->condition('entity_id', $entity->id())
      ->condition('value', \Drupal::request()->get($tokenKey))
      ->execute();

    if ($tokens) {

      $token = \Drupal::entityTypeManager()
        ->getStorage('access_token')
        ->load(current($tokens));

      if (!$token->isExpired()) {
        return AccessResult::allowed()
          ->cachePerPermissions()
          ->setCacheMaxAge($token->get('expire')->value - REQUEST_TIME);

      }

    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_form_alter().
 */
function access_unpublished_form_alter(&$form, FormStateInterface $form_state) {

  if (!$form_state->getFormObject() instanceof EntityForm) {
    return;
  }

  /** @var \Drupal\Core\Entity\Entity $entity */
  $entity = $form_state->getFormObject()->getEntity();

  // @todo: For 8.3 this should check for EntityPublishedInterface.
  if ($entity instanceof NodeInterface && !$entity->isPublished() && !$entity->isNew()) {

    $storage = \Drupal::entityTypeManager()->getStorage('access_token');

    $query = $storage->getQuery();
    $tokens = $query->condition('entity_type', $entity->getEntityType()->id())
      ->condition('entity_id', $entity->id())
      ->execute();

    $form['#attached']['library'][] = 'access_unpublished/drupal.access_unpublished.admin';

    // Create the group for the fields.
    $form['access_unpublished_settings'] = array(
      '#type' => 'details',
      '#title' => t('Temporary unpublished access'),
      '#open' => !empty($tokens),
      '#weight' => 35,
      '#attributes' => array(
        'class' => array('access-unpublished-form'),
      ),
      '#optional' => FALSE,
      '#group' => 'advanced',
    );

    if ($tokens) {

      /** @var \Drupal\access_unpublished\Entity\AccessToken[] $tokens */
      $tokens = $storage->loadMultiple($tokens);

      $form['access_unpublished_settings']['token_table'] = array(
        '#type' => 'table',
        '#header' => array(
          t('Valid'),
          t('Link'),
          t('Expire date'),
          t('Operations'),
        ),
      );

      $tokenKey = \Drupal::config('access_unpublished.settings')
        ->get('hash_key');

      foreach ($tokens as $id => $token) {

        $form['access_unpublished_settings']['token_table'][$id]['expired'] = array(
          '#type' => 'checkbox',
          '#default_value' => !$token->isExpired(),
          '#disabled' => TRUE,
        );

        $url = Url::fromRoute('entity.' . $entity->getEntityType()
            ->id() . '.canonical',
          [
            $entity->getEntityType()->id() => $entity->id(),
            $tokenKey => $token->get('value')->value,
          ],
          [
            'absolute' => TRUE,
          ]
        )->toString();

        $form['access_unpublished_settings']['token_table'][$id]['link'] = [
          '#type' => 'button',
          '#value' => t('Copy to clipboard'),
          '#attributes' => [
            'data-clipboard-text' => $url,
            'class' => ['clipboard-button'],
          ],
        ];
        $form['access_unpublished_settings']['token_table'][$id]['expire_date'] = array(
          '#plain_text' => $token->get('expire')->value > 0 ? format_date($token->get('expire')->value) : t('Unlimited'),
        );
        $form['access_unpublished_settings']['token_table'][$id]['operations'] = array(
          '#type' => 'operations',
          '#links' => array(),
        );

        if ($token->isExpired()) {
          $form['access_unpublished_settings']['token_table'][$id]['operations']['#links']['renew'] = array(
            'title' => t('Renew'),
            'url' => Url::fromRoute('access_unpublished.access_token_controller_renew', array('id' => $id)),
          );
        }
        else {
          $form['access_unpublished_settings']['token_table'][$id]['operations']['#links']['delete'] = array(
            'title' => t('Delete'),
            'url' => Url::fromRoute('access_unpublished.access_token_controller_delete', array('id' => $id)),
          );
        }
      }
    }

    $duration = \Drupal::config('access_unpublished.settings')->get('duration');

    $form['access_unpublished_settings']['duration'] = [
      '#type' => 'select',
      '#title' => t('Lifetime'),
      '#options' => [
        86400 => t('@days Days', ['@days' => 1]),
        172800 => t('@days Days', ['@days' => 2]),
        345600 => t('@days Days', ['@days' => 4]),
        604800 => t('@days Days', ['@days' => 7]),
        1209600 => t('@days Days', ['@days' => 14]),
        -1 => t('Unlimited'),
      ],
      '#default_value' => $duration,
    ];

    $form['access_unpublished_settings']['generate_token'] = array(
      '#type' => 'submit',
      '#value' => t('Generate token'),
      '#submit' => ['access_unpublished_generate_token'],
    );
  }
}

/**
 * Submit callback to generate a token.
 *
 * @param array $form
 *   Form array.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function access_unpublished_generate_token(&$form, FormStateInterface $form_state) {

  /** @var \Drupal\Core\Entity\Entity $entity */
  $entity = $form_state->getFormObject()->getEntity();
  \Drupal::entityTypeManager()->getStorage('access_token')->create(
    [
      'entity_type' => $entity->getEntityType()->id(),
      'entity_id' => $entity->id(),
      'expire' => $form_state->getValue('duration') > 0 ? REQUEST_TIME + $form_state->getValue('duration') : -1,
    ]
  )->save();

  $form_state->setRebuild();
}
