<?php

/**
 * @file
 * Contains common funtions for TAL default content module.
 */

/**
 * Import a piece of content exported by default content module.
 *
 * @param string $path_to_content_json
 *   Path to json file.
 */
function tal_default_content_import($path_to_content_json) {
  list($entity_type_id, $filename) = explode('/', $path_to_content_json);
  $p = drupal_get_path('module', 'tal_default_content');
  $encoded_content = file_get_contents($p . '/content/' . $path_to_content_json);
  $serializer = \Drupal::service('serializer');
  $content = $serializer->decode($encoded_content, 'hal_json');
  global $base_url;
  $url = $base_url . base_path();
  $content['_links']['type']['href'] = str_replace('http://drupal.org/', $url, $content['_links']['type']['href']);
  $contents = $serializer->encode($content, 'hal_json');

  // The class structure for taxonomy terms is different.
  if ($entity_type_id == 'taxonomy_term') {
    $class = 'Drupal\taxonomy\Entity\term';
  }
  else {
    $class = 'Drupal\\' . $entity_type_id . '\Entity\\' . str_replace(' ', '', ucwords(str_replace('_', ' ', $entity_type_id)));
  }

  $entity = $serializer->deserialize($contents, $class, 'hal_json', array('request_method' => 'POST'));
  $entity->enforceIsNew(TRUE);
  $entity->save();
}
