<?php

/**
 * @file
 * Update scripts for the TAL default content module.
 */

/**
 * Add the Article category terms.
 *
 * Implements hook_update_N().
 */
function tal_default_content_update_8001() {
  // Create Article category terms 'Events' and 'Press Release'.
  tal_default_content_import('taxonomy_term/article-category-press-release.json');
  tal_default_content_import('taxonomy_term/article-category-events.json');
}
