<?php

/**
 * @file
 * Contains hook_field_widget_form_alter hook.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 */
function tal_image_widget_field_widget_form_alter(&$element, FormStateInterface &$form_state, $context) {
  // Check if the is FileBrowserWidget or not.
  if (get_class($context['widget']) === 'Drupal\entity_browser\Plugin\Field\FieldWidget\FileBrowserWidget' && !empty($context['form']['#attributes'])) {
    // Check if the value is present for Image field or not.
    if (!empty($element['target_id']['#default_value'])) {
      // Get Image field value which contains fids.
      $fids_string = $element['target_id']['#default_value'];
      $fids = explode(" ", $fids_string);
      foreach ($fids as $fid) {
        $fid = substr($fid, 5);
        // Get media ID from the file ID.
        $media_image_id = \Drupal::database()
          ->select('media__image', 'mi')
          ->fields('mi', ['entity_id'])
          ->condition('image_target_id', $fid, '=')
          ->execute()->fetchField();

        if (!empty($media_image_id)) {
          // Load Media entity.
          $media = \Drupal::entityTypeManager()->getStorage('media')->load($media_image_id);
          $image_metadata = $media->get('image')->getValue();
          // Add default ALT value if not present from media entity.
          if (empty($element['current'][$fid]['meta']['alt']['#default_value'])) {
            $element['current'][$fid]['meta']['alt']['#default_value'] = $image_metadata[0]['alt'];
          }
          // Add default TITLE value if not present from media entity.
          if (empty($element['current'][$fid]['meta']['title']['#default_value'])) {
            $element['current'][$fid]['meta']['title']['#default_value'] = $image_metadata[0]['title'];
          }
        }
      }
    }
  }
}
