token_login.settings:
  type: mapping
  label: 'Token Login Settings'
  mapping:
    langcode:
      type: string
      label: 'Language code'
    default_langcode:
      type: string
      label: 'Site default language code'
    allowed_domains:
      type: string
      label: 'List of domains for which email login can be requested'
    message:
      type: text
      label: 'Contents of the login email including placeholder tokens'
