tal_admin_config.tal_settings:
  title: 'Administer Tate & Lyle'
  route_name: tal_admin_config.tal_settings
  description: 'Configure Tate & Lyle Settings.'
  parent: system.admin_config
  weight: 99
tal_admin_config.tal_admin_trendsandinsight:
  title: 'Tate & Lyle Settings'
  route_name: tal_admin_config.tal_admin_trendsandinsight
  description: 'Configure Tate & Lyle Settings.'
  parent: tal_admin_config.tal_settings
  weight: 99
